# Generated by Django 3.1.5 on 2021-02-03 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0005_remove_bookmark_deleted_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank='True', max_length=255),
        ),
    ]
