# Generated by Django 3.1.5 on 2021-01-29 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_language'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='state',
            new_name='district',
        ),
    ]
