# Generated by Django 3.1.5 on 2021-01-31 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210131_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='district',
            new_name='state',
        ),
    ]
