# Generated by Django 3.1.6 on 2021-02-05 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='WorkGallery/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_gallery', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
