# Generated by Django 3.1.5 on 2021-01-29 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210129_0621'),
        ('profiles', '0002_profile_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='users', to='core.Language'),
        ),
    ]
